### ISSUE TITLE
[Bug]: 在最新的Hexo版本中出现报错

### ISSUE THREAD

**Issue by TNXG** [MaLuns/hexo-theme-async#76]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.0.5

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在最新的Hexo 7.0.0-rc1中，在渲染页面时出现如下报错
```
Unhandled rejection TypeError: C:\Users\tianx\Desktop\blog\themes\async\layout\index.ejs:1
 >> 1| <%- partial(theme.layout.main,  {
    2|     banner: partial(theme.layout.banner,  {
    3|         ...theme.banner.default,
    4|         bannerTitle: page.title,

C:\Users\tianx\Desktop\blog\themes\async\layout\_partial\page\index.ejs:4
    2| <% if(theme.categorie_card.enable) { %>
    3|     <div class="row hidden-sm">
 >> 4|         <%
    5|             let cards = []
    6|             if (Array.isArray(theme.categorie_card.list)) {
    7|                 theme.categorie_card.list.forEach(title => {

site.categories.data.sort is not a function
    at eval ("C:\\Users\\tianx\\Desktop\\blog\\themes\\async\\layout\\_partial\\page\\index.ejs":23:46)
    at index (C:\Users\tianx\Desktop\blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:122:32)
    at _View.renderSync (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:64:29)
    at Object.partial (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("C:\\Users\\tianx\\Desktop\\blog\\themes\\async\\layout\\index.ejs":16:14)
    at index (C:\Users\tianx\Desktop\blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:50:21)
    at C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\hexo\index.js:58:29
    at tryCatcher (C:\Users\tianx\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\tianx\Desktop\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Unhandled rejection TypeError: C:\Users\tianx\Desktop\blog\themes\async\layout\index.ejs:1
 >> 1| <%- partial(theme.layout.main,  {
    2|     banner: partial(theme.layout.banner,  {
    3|         ...theme.banner.default,
    4|         bannerTitle: page.title,

C:\Users\tianx\Desktop\blog\themes\async\layout\_partial\page\index.ejs:4
    2| <% if(theme.categorie_card.enable) { %>
    3|     <div class="row hidden-sm">
 >> 4|         <%
    5|             let cards = []
    6|             if (Array.isArray(theme.categorie_card.list)) {
    7|                 theme.categorie_card.list.forEach(title => {

site.categories.data.sort is not a function
    at eval ("C:\\Users\\tianx\\Desktop\\blog\\themes\\async\\layout\\_partial\\page\\index.ejs":23:46)
    at index (C:\Users\tianx\Desktop\blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:122:32)
    at _View.renderSync (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:64:29)
    at Object.partial (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("C:\\Users\\tianx\\Desktop\\blog\\themes\\async\\layout\\index.ejs":16:14)
    at index (C:\Users\tianx\Desktop\blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\theme\view.js:50:21)
    at C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\hexo\index.js:58:29
    at tryCatcher (C:\Users\tianx\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\tianx\Desktop\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\tianx\Desktop\blog\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
tips: 正在尝试更换主题，最新的Hexo版本出现如上报错，在Hexo 6.3.0下可以正常使用（配置还没调完

![image](https://user-images.githubusercontent.com/69001561/229348009-3c15518e-c463-4866-b97c-68746269e197.png)

### 出现问题网站 | Website

https://blog.tnxg.top

**Comment by MaLuns** [comment]
应该是 Hexo 的 site.categories 变量数据结构发生了变化，等 Hexo 正式版发布后会跟进
